/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    briefs: Brief;
    orders: Order;
    quotes: Quote;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    briefs: BriefsSelect<false> | BriefsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'api') | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs".
 */
export interface Brief {
  id: number;
  diagnosis?: ('biuro' | 'strona' | 'sprzedaz' | 'wizja') | null;
  industry?: string | null;
  size?: string | null;
  tools?: string | null;
  clientName: string;
  clientEmail: string;
  phone?: string | null;
  company: string;
  nip?: string | null;
  problemDescription: string;
  hoursWeek?: number | null;
  peopleInvolved?: string | null;
  growsWithScale?: string | null;
  triedBefore?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  triedNotes?: string | null;
  urgency?: ('palace' | 'miesiac' | 'kwartal' | 'rozwazam') | null;
  scope?: ('mvp' | 'pelny' | 'doradzcie') | null;
  budget?: string | null;
  agreedPrivacy: boolean;
  agreedTerms: boolean;
  status?: ('new' | 'contacted' | 'quoted' | 'change_requested' | 'won' | 'lost') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  briefId?: (number | null) | Brief;
  stripeEventId?: string | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  amount: number;
  currency: string;
  status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  customerEmail?: string | null;
  billingName?: string | null;
  billingPhone?: string | null;
  billingCompanyName?: string | null;
  billingNip?: string | null;
  billingStreet?: string | null;
  billingCity?: string | null;
  billingPostalCode?: string | null;
  billingCountry?: string | null;
  payments?:
    | {
        stripeInvoiceId?: string | null;
        amount?: number | null;
        paidAt?: string | null;
        status?: ('paid' | 'failed') | null;
        fakturaXlInvoiceId?: string | null;
        invoiceStatus?: ('sent' | 'error') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  title: string;
  brief: number | Brief;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected') | null;
  quoteToken?: string | null;
  content?:
    | (
        | {
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            phaseName: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
      )[]
    | null;
  totalPrice: number;
  maintenancePrice?: number | null;
  maintenanceDescription?: string | null;
  clientSelectedMaintenance?: boolean | null;
  /**
   * Aktualizowane przez webhook Stripe.
   */
  paymentStatus?: ('unpaid' | 'paid_half' | 'paid_full') | null;
  orderId?: (number | null) | Order;
  quoteSentAt?: string | null;
  /**
   * Zaznacz to pole i kliknij Zapisz, aby wysłać maila do klienta.
   */
  actionSendQuote?: boolean | null;
  /**
   * Wysyła maila z linkiem do podpięcia karty na poczet abonamentu za utrzymanie.
   */
  actionSendSubscription?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'briefs';
        value: number | Brief;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs_select".
 */
export interface BriefsSelect<T extends boolean = true> {
  diagnosis?: T;
  industry?: T;
  size?: T;
  tools?: T;
  clientName?: T;
  clientEmail?: T;
  phone?: T;
  company?: T;
  nip?: T;
  problemDescription?: T;
  hoursWeek?: T;
  peopleInvolved?: T;
  growsWithScale?: T;
  triedBefore?: T;
  triedNotes?: T;
  urgency?: T;
  scope?: T;
  budget?: T;
  agreedPrivacy?: T;
  agreedTerms?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  briefId?: T;
  stripeEventId?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  customerEmail?: T;
  billingName?: T;
  billingPhone?: T;
  billingCompanyName?: T;
  billingNip?: T;
  billingStreet?: T;
  billingCity?: T;
  billingPostalCode?: T;
  billingCountry?: T;
  payments?:
    | T
    | {
        stripeInvoiceId?: T;
        amount?: T;
        paidAt?: T;
        status?: T;
        fakturaXlInvoiceId?: T;
        invoiceStatus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  title?: T;
  brief?: T;
  status?: T;
  quoteToken?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              phaseName?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
      };
  totalPrice?: T;
  maintenancePrice?: T;
  maintenanceDescription?: T;
  clientSelectedMaintenance?: T;
  paymentStatus?: T;
  orderId?: T;
  quoteSentAt?: T;
  actionSendQuote?: T;
  actionSendSubscription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}