/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    briefs: Brief;
    orders: Order;
    quotes: Quote;
    media: Media;
    documents: Document;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    briefs: BriefsSelect<false> | BriefsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'api') | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Wpisz nazwę firmy, imię lub email żeby filtrować w wyszukiwarce.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs".
 */
export interface Brief {
  id: number;
  diagnosis?: ('biuro' | 'strona' | 'sprzedaz' | 'wizja') | null;
  industry?: string | null;
  size?: string | null;
  tools?: string | null;
  clientName: string;
  clientEmail: string;
  phone?: string | null;
  company: string;
  nip?: string | null;
  problemDescription: string;
  attachments?: (number | Media)[] | null;
  hoursWeek?: number | null;
  laborRate?: ('low' | 'mid' | 'high') | null;
  peopleInvolved?: string | null;
  growsWithScale?: string | null;
  triedBefore?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  triedNotes?: string | null;
  urgency?: ('low' | 'medium' | 'high' | 'urgent') | null;
  scope?: ('mvp' | 'pelny' | 'doradzcie') | null;
  budget?: string | null;
  agreedPrivacy: boolean;
  agreedTerms: boolean;
  status?: ('new' | 'contacted' | 'quoted' | 'change_requested' | 'won' | 'lost') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  briefId?: (number | null) | Brief;
  stripeEventId?: string | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  amount: number;
  currency: string;
  status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  customerEmail?: string | null;
  billingName?: string | null;
  billingPhone?: string | null;
  billingCompanyName?: string | null;
  billingNip?: string | null;
  billingStreet?: string | null;
  billingCity?: string | null;
  billingPostalCode?: string | null;
  billingCountry?: string | null;
  payments?:
    | {
        amount?: number | null;
        paidAt?: string | null;
        status?: ('paid' | 'failed') | null;
        fakturaXlInvoiceId?: string | null;
        invoiceStatus?: ('sent' | 'error') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wyceny dla klientów. Uzupełnij treść, ustaw cenę i kliknij "Wyślij wycenę do klienta".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * Tylko do użytku wewnętrznego. Klient tego nie widzi.
   */
  title: string;
  /**
   * Wpisz nazwę firmy, imię lub email klienta żeby znaleźć odpowiedni brief.
   */
  brief: number | Brief;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected') | null;
  /**
   * Auto-generowany. Klient wchodzi przez /wycena/{token}
   */
  quoteToken?: string | null;
  /**
   * Markdown: **pogrubienie**, *kursywa*, ## nagłówek, - lista, 1. lista numerowana, [tekst](https://...), > cytat. Pusta linia = nowy akapit.
   */
  intro?: string | null;
  /**
   * Etapy projektu. Np. "### Faza 1 — Analiza" + lista pod spodem. Obsługuje pełny Markdown.
   */
  timelinePlan?: string | null;
  /**
   * Co wchodzi w zakres, a co nie. Użyj list: "- Pozycja w zakresie". Obsługuje pełny Markdown.
   */
  scopePlan?: string | null;
  /**
   * Klient widzi rabat 10% przy płatności jednorazowej.
   */
  totalPrice: number;
  /**
   * Zostaw puste jeśli nie oferujesz utrzymania.
   */
  maintenancePrice?: number | null;
  maintenanceDescription?: string | null;
  /**
   * Aktualizowane przez klienta na stronie wyceny.
   */
  clientSelectedMaintenance?: boolean | null;
  /**
   * Aktualizowane automatycznie przez webhook Stripe.
   */
  paymentStatus?: ('unpaid' | 'paid_half' | 'paid_full') | null;
  /**
   * Wypełniane automatycznie po płatności.
   */
  orderId?: (number | null) | Order;
  /**
   * Aktualizowane automatycznie przez webhook Stripe.
   */
  subscriptionStatus?: ('none' | 'active' | 'canceled') | null;
  stripeSubscriptionId?: string | null;
  stripeCustomerId?: string | null;
  /**
   * Zapisywane automatycznie z checkoutu Stripe przy aktywacji subskrypcji. Używane przez FakturaXL przy każdej płatności cyklicznej.
   */
  subscriptionBilling?: {
    companyName?: string | null;
    nip?: string | null;
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    phone?: string | null;
  };
  /**
   * Zapisywane automatycznie przy pierwszej płatności. Tylko do odczytu.
   */
  consent?: {
    acceptedAt?: string | null;
    ip?: string | null;
    email?: string | null;
    agreementAccepted?: boolean | null;
    documents?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  quoteSentAt?: string | null;
  subscriptionSentAt?: string | null;
  finalPaymentSentAt?: string | null;
  actionSendQuote?: boolean | null;
  actionSendSubscription?: boolean | null;
  actionSendFinalPayment?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dokumenty prawne pokazywane klientom. Edycja treści automatycznie podbija wersję i hash.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Jeden dokument na rodzaj (unikalny).
   */
  docType: 'umowa-wspolpracy' | 'regulamin' | 'polityka-prywatnosci' | 'rodo';
  title: string;
  /**
   * Markdown: **pogrubienie**, ## nagłówek, - lista, [link](https://...). Pusta linia = nowy akapit.
   */
  content: string;
  /**
   * Auto: rośnie przy każdej zmianie treści.
   */
  version?: string | null;
  /**
   * Odcisk treści — dowód, na jaką wersję zgodził się klient.
   */
  contentHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'briefs';
        value: number | Brief;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs_select".
 */
export interface BriefsSelect<T extends boolean = true> {
  diagnosis?: T;
  industry?: T;
  size?: T;
  tools?: T;
  clientName?: T;
  clientEmail?: T;
  phone?: T;
  company?: T;
  nip?: T;
  problemDescription?: T;
  attachments?: T;
  hoursWeek?: T;
  laborRate?: T;
  peopleInvolved?: T;
  growsWithScale?: T;
  triedBefore?: T;
  triedNotes?: T;
  urgency?: T;
  scope?: T;
  budget?: T;
  agreedPrivacy?: T;
  agreedTerms?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  briefId?: T;
  stripeEventId?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  customerEmail?: T;
  billingName?: T;
  billingPhone?: T;
  billingCompanyName?: T;
  billingNip?: T;
  billingStreet?: T;
  billingCity?: T;
  billingPostalCode?: T;
  billingCountry?: T;
  payments?:
    | T
    | {
        amount?: T;
        paidAt?: T;
        status?: T;
        fakturaXlInvoiceId?: T;
        invoiceStatus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  title?: T;
  brief?: T;
  status?: T;
  quoteToken?: T;
  intro?: T;
  timelinePlan?: T;
  scopePlan?: T;
  totalPrice?: T;
  maintenancePrice?: T;
  maintenanceDescription?: T;
  clientSelectedMaintenance?: T;
  paymentStatus?: T;
  orderId?: T;
  subscriptionStatus?: T;
  stripeSubscriptionId?: T;
  stripeCustomerId?: T;
  subscriptionBilling?:
    | T
    | {
        companyName?: T;
        nip?: T;
        street?: T;
        city?: T;
        postalCode?: T;
        phone?: T;
      };
  consent?:
    | T
    | {
        acceptedAt?: T;
        ip?: T;
        email?: T;
        agreementAccepted?: T;
        documents?: T;
      };
  quoteSentAt?: T;
  subscriptionSentAt?: T;
  finalPaymentSentAt?: T;
  actionSendQuote?: T;
  actionSendSubscription?: T;
  actionSendFinalPayment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  docType?: T;
  title?: T;
  content?: T;
  version?: T;
  contentHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}